# Generated by Django 5.0.4 on 2024-05-20 17:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('vin', models.CharField(max_length=255)),
                ('license_plate', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_contact', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(default='Sedan', max_length=50)),
                ('seats', models.IntegerField(default=5)),
                ('cylinder', models.IntegerField(default=3)),
                ('drivetrain', models.CharField(default='Front Wheel Drive', max_length=255)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('child_seat', models.BooleanField(default=True)),
                ('zero_to_sixty', models.CharField(default='6.0 Seconds', max_length=255)),
                ('fuel_consumption', models.CharField(default='30 mpg', max_length=255)),
                ('option_camera', models.CharField(default='Backup Camera', max_length=255)),
                ('option_navigation', models.CharField(default='Navigation System', max_length=255)),
                ('option_carplay', models.CharField(default='Apple Carplay', max_length=255)),
                ('option_blindspot', models.CharField(default='Blind Spot Monitor', max_length=255)),
                ('option_parkingassist', models.CharField(default='Parking Assist', max_length=255)),
                ('option_sunroof', models.CharField(default='Sunroof', max_length=255)),
                ('option_heatcoolseat', models.CharField(default='Heated and Cooled Seat', max_length=255)),
                ('option_keyless', models.CharField(default='Keyless Start and Keyless Entry', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.car')),
            ],
        ),
        migrations.CreateModel(
            name='RentalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('driver_license', models.CharField(max_length=255)),
                ('driver_state', models.CharField(default='TX', max_length=2)),
                ('driver_address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('drop_off_date', models.DateField()),
                ('drop_off_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('rental_days', models.IntegerField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_rate', models.DecimalField(decimal_places=2, default=39.0, max_digits=10)),
                ('credit_card_number', models.IntegerField(default=0)),
                ('billing_address', models.CharField(default='', max_length=255)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('security_number', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='api.car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
